name: rubisUHC
version: 1.0
author: GameBlack
main: fr.gameblack.rcuhcv2.Main
api-version: 1.8.9
load: startup
commands:
  fastcreate:
    description: creation
  addpoints:
    description : Permet d'ajouter des points pour les rôles Toinou & démon Ange
    permission: rcuhc.addpoints
  addrole:
    description: Ajoute un rôle à la compo
  removerole:
    description: Retire un rôle de la compo
  doc:
    description: Lien du doc
  setgroup:
    description: Permet à l'host de set la limite de groupe
  rcme:
    description: Permet d'afficher votre rôle et ses pouvoirs
  rcrepair:
    decription: Commande du role Captain
  rcenchant:
    decription: Commande du role Captain
  rcshop:
    description: Commande du role Toinou
  rcclasse:
    description: Commande du role GameBlack
  rcbuff:
    description: Commande du role GameBlack
  rccorruption:
    description: Commande du role Trial
  rclist:
    description: Permet de voir la liste des joueurs en vie
  rcpartage:
    description: Commande du role Jeannot
  rcabso:
    description: Commande du role Jeannot
  rcpapier:
    description: Commande du role Nickoboop
  rctrial:
    description: Commande du role Slup
  rcmort:
    description: Commande du role Slup
  rcslime:
    description: Commande du role Slup
  rccube:
    description: Commande du role Joko
  rcsteal:
    description: Commande du role Joko
  rchack:
    description: Commande du role Farmeurimmo
  rcvol:
    description: Commande du role Farmeurimmo
  rccamp:
    description: Commande du role Farmeurimmo
  rcban:
    description: Commande du role Kzou
  rcdisperse:
    description: Commande du role Kzou
  rcop:
    description: Commande du role Kzou
  rcplay:
    description: Commande du role Trial
  rcmode:
    description: Commande du role Trial
  rcsacrifice:
    description: Commande du role Trial
  firstreflexgame:
    description: Null
  rcserveur:
    description: Commande du role Loup
  rcbateau:
    description: Commande du role Loup
  rcchangeorbe:
    description: Commande du role GameBlack
  rccheckorbe:
    description: Commande du role GameBlack
  rcconsole:
    description: Commande du role GameBlack
  rcforme:
    description: Commande du role Maka
  rcvacance:
    description: Commande du role Toinou
  rctraque:
    description: Commande du role Toinou
  rcmaudit:
    description: Commande du role Obscur
  seeall:
    description: Permet d'afficher tt les joueurs
  rcinfo:
    description: Commande pour les rôles Trial et Farmeurimmo
  fermeturegolden:
    description: Permet d'activer l'évènement "Fermeture de golden"
    permission: rcuhcv2.fermeturegolden
  spawnminerais:
    description: Permet de faire apparaître un minerais
    permission: rcuhcv2.spawnminerais
  setrole:
    description: Permet de donner un role
    permission: rcuhcv2.setrole
  setroleother:
    description: Permet de donner un role à un autre joueur
    permission: rcuhcv2.setroleother
  setorbe:
    description: Permet de donner une orbe
    permission: rcuhcv2.setorbe
  setstatut:
    description: Permet de changer le statut de la partie
    permission: rcuhcv2.setstatut
  skipepisode:
    description: Permet de passer un épisode
    permission: rcuhcv2.skipepisode
  compo:
    description: Permet de voir la compo de la partie
  rceffet:
    description: Permet de voir ses pourcentage d'effets
  rcorbe:
    description: Permet de désactiver/activer son orbe
  addallrole:
    description: Permet d'ajouter tous les rôles fonctionnel à la compo
  addallrolepvp:
    description: Permet d'ajouter tous les rôles fonctionnel à la compo
  create:
    description: Permet de créer une partie (Commande host)
  start:
    description: Permet de démarrer la partie (Commande host)
    
  rcback:
    description: Commande du rôle GameBlack
  rcchoose:
    description: Commande du rôle GameBlack
  rcflair:
    description: Commande du rôle GameBlack
  rcinspect:
    description: Commande du rôle GameBlack
  rcnerf:
    description: Commande du rôle GameBlack
  rcdemon:
    description: Commande du rôle GameBlack
  rcdon:
    description: Commande du rôle Maka
  rcbroken:
    description: Commande du rôle Trial
  rccopie:
    description: Commande du rôle Obscur
  rcsetpiece:
    description: Commande du rôle Obscur
  rckill:
    description: Commande du rôle Cosmos
  rcsang:
    description: Commande du rôle Sang
  rcblind:
    description: Commande du rôle Tenebre
  rcnuit:
    description: Commande du rôle Tenebre