package fr.gameblack.rcuhcv2;

public enum Debug {
	RAPTOR, JEANNOT, NICKOBOOP, JOKO, SLUP, TEAM, GAMEBLACK, MAKA, TRIAL, LOUP, CAPTAIN, HEKOW, MALIVOL, TOINOU, OBSCUR, NONOBOY, FARMEURIMMO, KZOU, ORBE, DEGAT, SCOREBOARD, MINERAIS, FERMETURE_GOLDEN, GIVEROLE, HOST, STATUT
}
