package fr.gameblack.rcuhcv2;

public enum Pouvoirs {
	
	RAPTOR_RAGE, RAPTOR_CHEAT, NICKOBOOP_PAPIER, JOKO_CUBE, MALIVOL_CHEAT, FARMEURIMMO_HACK, SLUP_RCTRIAL, LOUP_SERVEUR, TOINOU_VACANCES, KZOU_DISPERSE, KZOU_BAN, LOUP_SUPERBATEAU
	
}
