package fr.gameblack.rcuhcv2;

public enum Pouvoirs {
	
	TEAM_JUSTICE, OBSCUR_ADAPTION, MAKA_NEKO, RAPTOR_RAGE, RAPTOR_CHEAT, NICKOBOOP_PAPIER, NICKOBOOP_PROCHE_JEANNOT, JOKO_CUBE, JOKO_GIVECUBE, MALIVOL_CHEAT, FARMEURIMMO_HACK, SLUP_RCTRIAL, SLUP_MORT, SLUP_SLIME, LOUP_SERVEUR, GAMEBLACK_CHECKORBE, GAMEBLACK_CONSOLE, GAMEBLACK_FUITE, GAMEBLACK_MALUS_ORBE, TOINOU_VACANCES, KZOU_DISPERSE, KZOU_BAN, LOUP_SUPERBATEAU, EFFET, TRIAL_FORCE_KILL, TRIAL_JEU, TRIAL_CORRUPTION, TRIAL_BENIHIME, TRIAL_SAKASHIMA, NONOBOY_COEUR_KILL, MALUS_ORBE_EAU, MALUS_ORBE_FEU, MALUS_ORBE_GLACE, MALUS_ORBE_FOUDRE
	
}
