package fr.gameblack.rubisuhc;

public enum Pouvoirs {

	GB_NERF, GB_RECRUT, GB_INSPECT, LOUP_TRANSFO, RAPTOR_RAGE, TENEBRE_BLIND, SANG_SANG, COSMOS_ZONE, ENFER_ZONE, MALEDICTION_MAUDIT, TRONCONEUSE_LAME, KZOU_DISPERSE, KZOU_BAN, ELECTRIQUE_FOUDRE, ELECTRIQUE_SACRIFICE, EXPERIMENTAL_SACRIFICE, JOKO_CUBE, JOKO_GIVECUBE, MAKA_DON, MALIVOL_CHEAT
	
}
