package fr.gameblack.rcuhcv2.classes.v1;

public enum VolTrial {
	
	SLUP, MALIVOL, OBSCUR, ANGE, AVENIR, COSMOS, DEMON, ENFER, ENFER_SACRIFICE, MALEDICTION, MALEDICTION_SACRIFICE, SANG, TRONCONNEUSE, TENEBRE, OK
	
}
