package fr.gameblack.rubisuhc;

public enum Roles {

    GAMEBLACK, TEAM, MAKA, LOUP, RAPTOR, JOKO, GUERRIER, ARCHER, ECLAIREUR, TRIAL, SLUP, FARMEURIMMO, TENEBRE, SANG, COSMOS, ENFER, MALEDICTION, ELECTRIQUE, ANGE, AVENIR, DEMON, TOINOU, KZOU, MALIVOL, EXPERIMENTAL, TRONCONEUSE, OBSCUR, NONE

}
