package fr.gameblack.rcuhcv2.classes;

public enum Pouvoirs {
	
	YURI_AZIZ, JEANNOT_ABSO, THEOOCHOUX_MINIROLLBACK, THEOOCHOUX_ROLLBACK, HEKOW_JEU, CAPTAIN_REPAIR, CAPTAIN_ENCHANT_SELF, CAPTAIN_ENCHANT_OTHER, TEAM_JUSTICE, TEAM_INVISIBLE, OBSCUR_ADAPTION, MAKA_NEKO, RAPTOR_RAGE, RAPTOR_CHEAT, NICKOBOOP_PAPIER, NICKOBOOP_PROCHE_JEANNOT, JOKO_CUBE, JOKO_GIVECUBE, MALIVOL_CHEAT, FARMEURIMMO_HACK, SLUP_RCTRIAL, SLUP_MORT, SLUP_SLIME, LOUP_SERVEUR, GAMEBLACK_CHECKORBE, GAMEBLACK_CONSOLE, GAMEBLACK_FUITE, GAMEBLACK_MALUS_ORBE, TOINOU_VACANCES, KZOU_DISPERSE, KZOU_BAN, LOUP_SUPERBATEAU, EFFET, TRIAL_FORCE_KILL, TRIAL_JEU, TRIAL_CORRUPTION, TRIAL_BENIHIME, TRIAL_SAKASHIMA, NONOBOY_COEUR_KILL, MALUS_ORBE_EAU, MALUS_ORBE_FEU, MALUS_ORBE_GLACE, MALUS_ORBE_FOUDRE,
	GB_NERF, GB_FLAIR, GB_INSPECT, GB_CAMOUFLAGE, LOUP_TRANSFO, TENEBRE_BLIND, SANG_SANG, COSMOS_ZONE, ENFER_ZONE, MALEDICTION_MAUDIT, TRONCONEUSE_LAME, ELECTRIQUE_FOUDRE, ELECTRIQUE_SACRIFICE, EXPERIMENTAL_SACRIFICE, MAKA_DON, TRIAL_BANKAI, OBSCUR_ORBE, TRONCONNEUSE_SAIGNEMENT, TENEBRE_KILL, ENFER_FEU
	
}
